### ISSUE TITLE
2020-02-13 오프모임

### ISSUE THREAD

**Issue by cjstk7168** [cjstk7168/AlgorithmStudy#10]
역삼역 20:00~ 예정입니다.

1. 총 4문제 중 1문제 리뷰 (돌아가며)
2. 앞으로의 진행 방향 논의!
3. 알고리즘 문제는 돌아가며 제출하는건 어떨까요.
4. 코드리뷰 방식 (반드시 review 승인해주세요 - 받은만큼 돌려주기)
5. 일주일 두 문제. 적은가 vs 적당한가 vs 많은가
6. 문제의 난이도. 쉽다/적당하다/어렵다

안건 1. 문제의 난이도. 쉽다/적당하다/어렵다
=> 적당하다
8:08
안건 2. 일주일 두 문제. 적은가 vs 적당한가 vs 많은가
=> 적당하다
8:09
안건 3. 알고리즘 문제는 돌아가며 제출하는건 어떨까요
=> 스터디장인님 경연님이
8:13
안건 4. 오프라인 모임은?
=> 월 1회 정도 알고리즘 회고, 스터디 그룹 회고
안건 5. pr 방식과 코드리뷰 방식
=> 지금대로
안건 6. 다른 언어 개발자를 배려하여 주석을 꼼꼼히

**Comment by cjstk7168** [comment]
1. 알고리즘 문제는 돌아가며 제출하는건 어떨까요.
2. 코드리뷰 방식 (반드시 review 승인해주세요 - 받은만큼 돌려주기)

**Comment by mitrvlr** [comment]
이번주 목요일 2/13 역삼역 20:00에 뵈어요~!!

<img width="333" alt="스크린샷 2020-02-10 오전 9 22 54" src="https://user-images.githubusercontent.com/24470477/74113365-f698ed00-4be6-11ea-8172-513a22e716a2.png">

**Comment by cjstk7168** [comment]
Q. 일주일 두 문제. 적은가 vs 적당한가 vs 많은가

**Comment by cjstk7168** [comment]
Q. 문제의 난이도. 쉽다/적당하다/어렵다
