### ISSUE TITLE
어떻게 하는 건지 잘 모르겠어요ㅠㅠ 

### ISSUE THREAD

**Issue by zynkn** [cjstk7168/AlgorithmStudy#8]
알려주세욥

**Comment by cjstk7168** [comment]
문제를 보시고, 현재 pr 2개 올라와있는데 올려주시면 됩니다!

1. 문제가 어려워서 모르겠다는 걸까요?
2. 올리는 방법을 모르겠다는 걸까요?

**Comment by zynkn** [comment]
전반적인 흐름을 모르겠어요ㅠㅠ

그냥 브랜치 따고, 문제 풀어서, 올리면 되나욥

**Comment by cjstk7168** [comment]
네 맞아요. https://github.com/cjstk7168/AlgorithmStudy/blob/master/README.md

PR규칙 보시고 pr 올려주시면 됩니다.
